# Generated by Django 4.2.3 on 2023-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_published_by_alter_book_published_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ol_id',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
