# Generated by Django 4.2.3 on 2023-07-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ol_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
