# Generated by Django 4.2.3 on 2023-07-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_ol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.location'),
        ),
    ]
