# Generated by Django 4.2.3 on 2023-08-04 11:04

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='illustrators',
            field=models.ManyToManyField(blank=True, related_name='illustrator_of', to='books.person'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[books.validators.validate_iso_639_pt3]),
        ),
        migrations.AddField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(blank=True, related_name='translator_of', to='books.person'),
        ),
    ]
