# Generated by Django 4.2.3 on 2023-08-04 11:24

import books.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_illustrators_book_language_book_translators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3, validators=[books.validators.validate_iso_639_pt3]), blank=True, null=True, size=None),
        ),
    ]
