# Generated by Django 4.2.3 on 2023-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_language_book_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
