# Generated by Django 4.2.3 on 2023-08-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_original_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='foreword_by',
            field=models.ManyToManyField(blank=True, related_name='foreword_by', to='books.person'),
        ),
    ]
